# Generated by Django 6.0.3 on 2026-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='poll_covers/'),
        ),
    ]
